server:
   port: ${SPRING_INVSER_PORT}

spring:
    application:
       name: ${SPRING_INVSER_NAME}
    banner:
        location: classpath:eshopInventoryBanner.txt
    datasource:
        continue-on-error: true
        initialization-mode: always
        initialize: true
        schema: classpath:/schema.sql
        password: ${SPRING_DATASOURCE_PASSWORD}
        url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DBNAME}
        username: ${SPRING_DATASOURCE_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    messages:
        basename: messages

eureka:
    instance:
        hostname: localhost
        preferIpAddress: true
#        lease-expiration-duration-in-seconds=1
#        lease-renewal-interval-in-seconds=2
    client:
        serviceUrl:
                defaultZone: http://${eureka.instance.hostname}:${SPRING_SERVER_PORT}/eureka
        register-with-eureka: true
        fetch-registry: true

logging:
    level:
        org:
            springframework: INFO
            springframework.security: TRACE
        eshop-inventory-service: INFO
