server:
#    port=${SPRING_COMSER_PORT}
    port: 8084

eureka:
    instance:
        hostname: localhost

spring:
    application:
#    	name=${SPRING_COMSER_NAME}
        name: eshop-communications-service
    datasource:
        continue-on-error: true
        initialization-mode: always
        initialize: true
        password: ${SPRING_DATASOURCE_PASSWORD}
        schema: classpath:/schema.sql
        url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DBNAME}
        username: ${SPRING_DATASOURCE_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    messages:
        basename: messages

logging:
    level:
        org:
            springframework: info
            springframework.security: TRACE

send:
    mail:
        from: ${SEND_MAIL_FROM}
        password: ${SEND_MAIL_PASSWORD}
